import Foundation

/// AI 子系统的文件布局。跟 capture 层一样统一在 `~/.portrait/` 下 ——
/// 单一数据目录,易于备份 / 清理 / 迁移。旧版本曾分到
/// `~/.portrait/`,启动时 `PathMigration` 把
/// 旧位置的文件搬过来。
enum AIPaths {
    static var supportDir: URL { Storage.rootURL }

    static var secretsDB: URL { supportDir.appendingPathComponent("secrets.sqlite") }
    static var chatDB: URL    { supportDir.appendingPathComponent("chat.sqlite") }
    static var bunDir: URL    { supportDir.appendingPathComponent("bun", isDirectory: true) }
    static var bunBinary: URL { bunDir.appendingPathComponent("bin/bun") }
    static var piDir: URL     { supportDir.appendingPathComponent("pi-agent", isDirectory: true) }
    static var piCliJS: URL   { piDir.appendingPathComponent("node_modules/@mariozechner/pi-coding-agent/dist/cli.js") }
    static var piModelsJSON: URL { piDir.appendingPathComponent("models.json") }

    /// AI agent 用的 CLI 工具目录(注入到 spawned subprocess 的 PATH 里)。
    /// 启动时把 app 主二进制 symlink 进这里成 `mp-query`,agent 通过 bash
    /// 直接调用拿屏幕数据。
    static var binDir: URL { supportDir.appendingPathComponent("bin", isDirectory: true) }
    static var mpQueryLink: URL { binDir.appendingPathComponent("mp-query") }
    static var mpFoldersLink: URL { binDir.appendingPathComponent("mp-folders") }

    /// AI agent 的对话 session 文件目录。每条 chat conv 对应一个文件,
    /// PiAgent 启动时 `--session <file>` 加载,ClaudeCodeAgent 走自己的
    /// `-r <sid>` 不落这里。conv 删除时连带删。
    static var agentSessionsDir: URL { supportDir.appendingPathComponent("agent_sessions", isDirectory: true) }
    /// 给一条 conv 派一个固定的 pi session jsonl 路径。pi 启动时如果文件
    /// 不存在会自动创建,存在就 open。
    static func piSessionPath(for convId: UUID) -> URL {
        agentSessionsDir.appendingPathComponent("\(convId.uuidString).jsonl")
    }

    static func ensureExists() throws {
        let fm = FileManager.default
        try fm.createDirectory(at: supportDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: binDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: agentSessionsDir, withIntermediateDirectories: true)
    }

    /// 启动时调一次。在 `~/.portrait/bin/mp-query` 写一个 shell wrapper,
    /// 内部 exec 当前 app 主二进制(绝对路径)+ `--mp-query "$@"`。
    ///
    /// **不能用 symlink** —— symlink 让 Swift `Bundle.main` 把 bundlePath
    /// 解析到 `~/.portrait/bin/`,mlx-swift 的 `Bundle.module` 找不到内嵌的
    /// `default.metallib`,binary 启动直接报 "MLX error: library not found"
    /// → exit 255。shell wrapper exec 主二进制绝对路径,argv[0] 是 .app
    /// 内部路径,Bundle 解析正常。
    ///
    /// app 升级后 exec 路径会变,所以每次启动都重写 wrapper。
    @discardableResult
    static func installMpQueryLink() -> Bool {
        installSkillWrapper(at: mpQueryLink, dispatchFlag: "--mp-query")
    }

    /// 同 installMpQueryLink,只是包装 `--mp-folders` 入口 —— chat AI 整理
    /// event folder 用。
    @discardableResult
    static func installMpFoldersLink() -> Bool {
        installSkillWrapper(at: mpFoldersLink, dispatchFlag: "--mp-folders")
    }

    /// 共用:在 binDir 下写一个 shell wrapper,exec 主二进制 + 指定 dispatch
    /// flag。每次 app 启动重写(app 升级后 exec 路径会变)。
    @discardableResult
    private static func installSkillWrapper(at url: URL, dispatchFlag: String) -> Bool {
        guard let exec = Bundle.main.executablePath else { return false }
        let fm = FileManager.default
        try? fm.createDirectory(at: binDir, withIntermediateDirectories: true)
        let path = url.path
        if fm.fileExists(atPath: path) {
            try? fm.removeItem(atPath: path)
        }
        let escaped = exec.replacingOccurrences(of: "\"", with: "\\\"")
        let wrapper = """
        #!/bin/sh
        # auto-generated by My Portrait — re-written on each app launch.
        exec "\(escaped)" \(dispatchFlag) "$@"
        """
        do {
            try wrapper.write(toFile: path, atomically: true, encoding: .utf8)
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: path)
            return true
        } catch {
            return false
        }
    }
}
