import Foundation

/// AI 子系统的文件布局。跟 capture 层一样统一在 `~/.portrait/` 下 ——
/// 单一数据目录,易于备份 / 清理 / 迁移。旧版本曾分到
/// `~/.portrait/`,启动时 `PathMigration` 把
/// 旧位置的文件搬过来。
enum AIPaths {
    static var supportDir: URL { Storage.rootURL }

    static var secretsDB: URL { supportDir.appendingPathComponent("secrets.sqlite") }
    static var chatDB: URL    { supportDir.appendingPathComponent("chat.sqlite") }
    static var bunDir: URL    { supportDir.appendingPathComponent("bun", isDirectory: true) }
    static var bunBinary: URL { bunDir.appendingPathComponent("bin/bun") }
    static var piDir: URL     { supportDir.appendingPathComponent("pi-agent", isDirectory: true) }
    static var piCliJS: URL   { piDir.appendingPathComponent("node_modules/@mariozechner/pi-coding-agent/dist/cli.js") }
    static var piModelsJSON: URL { piDir.appendingPathComponent("models.json") }

    /// AI agent 用的 CLI 工具目录(注入到 spawned subprocess 的 PATH 里)。
    /// 启动时把 app 主二进制 symlink 进这里成 `mp-query`,agent 通过 bash
    /// 直接调用拿屏幕数据。
    static var binDir: URL { supportDir.appendingPathComponent("bin", isDirectory: true) }
    static var mpQueryLink: URL { binDir.appendingPathComponent("mp-query") }

    static func ensureExists() throws {
        let fm = FileManager.default
        try fm.createDirectory(at: supportDir, withIntermediateDirectories: true)
        try fm.createDirectory(at: binDir, withIntermediateDirectories: true)
    }

    /// 启动时调一次。在 `~/.portrait/bin/mp-query` 写一个 shell wrapper,
    /// 内部 exec 当前 app 主二进制(绝对路径)+ `--mp-query "$@"`。
    ///
    /// **不能用 symlink** —— symlink 让 Swift `Bundle.main` 把 bundlePath
    /// 解析到 `~/.portrait/bin/`,mlx-swift 的 `Bundle.module` 找不到内嵌的
    /// `default.metallib`,binary 启动直接报 "MLX error: library not found"
    /// → exit 255。shell wrapper exec 主二进制绝对路径,argv[0] 是 .app
    /// 内部路径,Bundle 解析正常。
    ///
    /// app 升级后 exec 路径会变,所以每次启动都重写 wrapper。
    @discardableResult
    static func installMpQueryLink() -> Bool {
        guard let exec = Bundle.main.executablePath else { return false }
        let fm = FileManager.default
        let path = mpQueryLink.path
        try? fm.createDirectory(at: binDir, withIntermediateDirectories: true)
        // 旧的 symlink / 文件先清掉。
        if fm.fileExists(atPath: path) {
            try? fm.removeItem(atPath: path)
        }
        // sh-escape 路径里的双引号(理论上不会有,但防御)。
        let escaped = exec.replacingOccurrences(of: "\"", with: "\\\"")
        let wrapper = """
        #!/bin/sh
        # auto-generated by My Portrait — re-written on each app launch.
        # exec 主二进制 + --mp-query 子命令,把 stdin/stdout/stderr 一并继承。
        exec "\(escaped)" --mp-query "$@"
        """
        do {
            try wrapper.write(toFile: path, atomically: true, encoding: .utf8)
            // 加可执行权限。
            try fm.setAttributes([.posixPermissions: 0o755],
                                 ofItemAtPath: path)
            return true
        } catch {
            return false
        }
    }
}
