import Foundation
import OSLog
import AppKit

/// 一键导出诊断包到 Desktop:`My-Portrait-diagnostic-<ISO ts>.zip`。
///
/// 用户报 bug 时调这个,把生成的 zip 发给开发者。
///
/// **包含**(纯诊断,无内容):
///   - README.txt          —— 这个 bundle 装什么 / 不装什么
///   - system.json         —— app 版本 / macOS / 硬件 / 资源占用
///   - config-redacted.toml —— config.toml,密钥引用和 personal_info 全脱敏
///   - health.log          —— HealthMonitor fault/recover 历史
///   - stalls.json         —— StallDetector.recent (最近 50 条 verdict)
///   - processing_log.json —— processing_log 全表 (无 PII)
///   - db_stats.json       —— 各表 row count + ~/.portrait 子目录 du
///   - oslog-24h.jsonl     —— 过去 24h 所有 com.myportrait.* os.log
///
/// **不包含**:任何 .md / OCR full_text / typing 内容 / 转录文本 /
///   音视频文件 / SecretStore 密钥本体。
@MainActor
enum DiagnosticBundle {

    /// Build the bundle. 返回写好的 zip 的 URL。失败抛错由 UI 弹 alert。
    static func build() async throws -> URL {
        let isoFmt = ISO8601DateFormatter()
        isoFmt.formatOptions = [.withInternetDateTime, .withColonSeparatorInTime]
        let ts = isoFmt.string(from: Date()).replacingOccurrences(of: ":", with: "-")

        // 1) 临时工作目录(后面打包成 zip)
        let workDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("myportrait-diag-\(ts)", isDirectory: true)
        try? FileManager.default.removeItem(at: workDir)
        try FileManager.default.createDirectory(at: workDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: workDir) }

        // 2) 各组件写文件 —— 任何一项失败 swallow + 继续(把能拿的拿到)。
        writeText(readme, to: workDir.appendingPathComponent("README.txt"))
        try? writeSystemInfo(to: workDir.appendingPathComponent("system.json"))
        try? writeRedactedConfig(to: workDir.appendingPathComponent("config-redacted.toml"))
        try? copyHealthLog(to: workDir.appendingPathComponent("health.log"))
        try? writeStalls(to: workDir.appendingPathComponent("stalls.json"))
        try? writeProcessingLog(to: workDir.appendingPathComponent("processing_log.json"))
        try? writeDbStats(to: workDir.appendingPathComponent("db_stats.json"))
        try? writeOSLog24h(to: workDir.appendingPathComponent("oslog-24h.jsonl"))
        copyDiagnosticLogs(to: workDir)
        copyCrashReports(to: workDir)

        // 3) zip 到 Downloads(用户原话:放在 download 里)
        let downloads = try downloadsURL()
        let zipURL = downloads.appendingPathComponent("My-Portrait-diagnostic-\(ts).zip")
        try? FileManager.default.removeItem(at: zipURL)
        try runZip(srcDir: workDir, dstZip: zipURL)
        return zipURL
    }

    // MARK: - 子组件

    private static let readme = """
    My Portrait — Diagnostic Bundle
    ================================

    This bundle is a snapshot intended to help the developer diagnose a
    problem you reported. Generated by Settings → Health → "Export
    diagnostic bundle".

    INCLUDED (diagnostic only — no captured content):
      - system.json            app / macOS / hardware / disk usage
      - config-redacted.toml   your config with secrets removed
                               (API keys, personal info, names)
      - health.log             fault/recover history
      - stalls.json            recent stall detector verdicts
      - processing_log.json    memory-pipeline state table
      - db_stats.json          row counts per table, disk usage per dir
      - oslog-24h.jsonl        com.myportrait.* unified-log entries
      - diagnostic.log[.1-.5]  structured DiagLog history (rotating)
      - crash-reports/         recent MyPortrait crash reports (.ips), if any

    NOT INCLUDED (your data stays local):
      - any .md file (events, portrait, personality)
      - OCR text, typing events, transcriptions
      - audio/video/image files
      - secrets (API keys, OAuth tokens) — only metadata refs

    You can open the zip and inspect every file before sharing.
    """

    private static func writeText(_ s: String, to url: URL) {
        try? s.data(using: .utf8)?.write(to: url, options: .atomic)
    }

    /// system.json: app version + macOS + hardware + ~/.portrait 总大小
    private static func writeSystemInfo(to url: URL) throws {
        let info = Bundle.main.infoDictionary ?? [:]
        let proc = ProcessInfo.processInfo
        var dict: [String: Any] = [:]
        dict["app_version_marketing"] = info["CFBundleShortVersionString"] ?? "?"
        dict["app_version_build"]     = info["CFBundleVersion"] ?? "?"
        dict["app_bundle_id"]         = info["CFBundleIdentifier"] ?? "?"
        dict["macos_version"]         = proc.operatingSystemVersionString
        dict["physical_memory_bytes"] = proc.physicalMemory
        dict["processor_count"]       = proc.activeProcessorCount
        dict["host_arch"]             = (try? hostArch()) ?? "unknown"
        dict["app_uptime_sec"]        = Int(proc.systemUptime)
        dict["generated_at"]          = ISO8601DateFormatter().string(from: Date())
        dict["portrait_root_size_bytes"] = directorySize(Storage.rootURL)
        try writeJSON(dict, to: url)
    }

    /// 脱敏后的 config.toml: 把任何看似 secret / personal 的字段替换成占位符。
    /// 保留结构 + 数值/枚举字段(decay / budget / scheduler 时刻这些没隐私)。
    private static func writeRedactedConfig(to url: URL) throws {
        let cfg = ConfigStore.shared.current
        // 用 JSON 中转(TOML encode 走 TOMLKit 可能漏字段),最终就给开发者看,
        // 结构就行,不用真还原 .toml。
        let enc = JSONEncoder()
        enc.outputFormatting = [.prettyPrinted, .sortedKeys]
        var data = try enc.encode(cfg)
        // 文本层脱敏:任何带 "_ref" / "_key" 后缀的字段值清成 "***" (regex 替换);
        // personal_info 整块字段值改成 "<set>" / "<empty>" 标记。
        if var s = String(data: data, encoding: .utf8) {
            s = redactRefs(s)
            s = redactPersonalInfo(s, in: cfg)
            data = s.data(using: .utf8) ?? data
        }
        try data.write(to: url, options: .atomic)
    }

    private static func redactRefs(_ s: String) -> String {
        // "<anyKey>_ref" : "..." → "***"
        let pattern = #""([A-Za-z0-9_]+)_(ref|key|token)"\s*:\s*"[^"]*""#
        return s.replacingOccurrences(
            of: pattern, with: "\"$1_$2\" : \"***\"",
            options: .regularExpression
        )
    }

    private static func redactPersonalInfo(_ s: String, in cfg: MyPortraitConfig) -> String {
        // 整段 personal_info 字符串值替换成 set/empty 标记。
        let pi = cfg.personalInfo
        let names = [pi.firstName, pi.middleName, pi.lastName, pi.alias,
                     pi.nationality, pi.ethnicity, pi.birthDate]
        var out = s
        for v in names where !v.isEmpty {
            out = out.replacingOccurrences(of: "\"\(v)\"", with: "\"<set>\"")
        }
        return out
    }

    /// DiagLog rolling files: diagnostic.log + diagnostic.log.1 ... .5。
    /// 全 copy 进 bundle —— rotating 加起来 ≤ 25MB,zip 后通常 ≤ 5MB。
    private static func copyDiagnosticLogs(to workDir: URL) {
        let fm = FileManager.default
        let base = DiagLog.logFileURL
        let candidates = [base] + (1...5).map { base.appendingPathExtension("\($0)") }
        for src in candidates where fm.fileExists(atPath: src.path) {
            let dst = workDir.appendingPathComponent(src.lastPathComponent)
            try? fm.copyItem(at: src, to: dst)
        }
    }

    /// 系统崩溃报告:~/Library/Logs/DiagnosticReports/ 下最近 5 份
    /// `MyPortrait-*.ips`(+ 老格式 `.crash`)拷进 bundle 的 `crash-reports/`。
    /// **排查闪退最关键的东西** —— 之前 bundle 漏了它,用户报闪退却没崩溃栈可看。
    /// 读真实 ~/Library(非容器),跟读 ~/.portrait 一致;读不到就 swallow。
    private static func copyCrashReports(to workDir: URL) {
        let fm = FileManager.default
        let reportsDir = fm.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Logs/DiagnosticReports", isDirectory: true)
        guard let items = try? fm.contentsOfDirectory(
            at: reportsDir,
            includingPropertiesForKeys: [.contentModificationDateKey],
            options: [.skipsHiddenFiles]) else { return }
        // 两类都要:
        //   - MyPortrait-<date>-….ips/.crash —— app 自己的代码崩溃(进程名 = MyPortrait)
        //   - JetsamEvent-<date>-….ips —— **OOM**:进程被系统 SIGKILL,不生成
        //     MyPortrait-*.ips,只进系统级 jetsam 报告。**闪退却没 .ips 多半是这个**,
        //     jetsam 报告里有被杀进程清单(含 MyPortrait + 内存占用)。
        let crashes = items.filter {
            let n = $0.lastPathComponent
            return ["ips", "crash"].contains($0.pathExtension.lowercased())
                && (n.hasPrefix("MyPortrait") || n.hasPrefix("JetsamEvent"))
        }
        guard !crashes.isEmpty else { return }
        let recent = crashes.sorted {
            let a = (try? $0.resourceValues(forKeys: [.contentModificationDateKey]))?
                .contentModificationDate ?? .distantPast
            let b = (try? $1.resourceValues(forKeys: [.contentModificationDateKey]))?
                .contentModificationDate ?? .distantPast
            return a > b
        }.prefix(8)
        let dstDir = workDir.appendingPathComponent("crash-reports", isDirectory: true)
        try? fm.createDirectory(at: dstDir, withIntermediateDirectories: true)
        for src in recent {
            try? fm.copyItem(at: src, to: dstDir.appendingPathComponent(src.lastPathComponent))
        }
    }

    /// 健康度日志:直接 copy ~/.portrait/logs/health.log。
    private static func copyHealthLog(to url: URL) throws {
        let src = HealthMonitor.logFileURL
        guard FileManager.default.fileExists(atPath: src.path) else {
            try writeText("(no health.log yet)", to: url)
            return
        }
        if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
        try FileManager.default.copyItem(at: src, to: url)
    }

    /// StallDetector.recent — 最近 50 条 verdict + 当前 IntentionalPauseState。
    private static func writeStalls(to url: URL) throws {
        let recent = StallDetector.shared.recent
        let pause = IntentionalPauseState.shared
        let payload: [String: Any] = [
            "generated_at": ISO8601DateFormatter().string(from: Date()),
            "pause_state": [
                "drm_active": pause.drmActive,
                "screen_asleep": pause.screenAsleep,
                "capture_disabled": pause.captureDisabled,
                "audio_transcription_paused": pause.audioTranscriptionPaused,
            ],
            "recent_verdicts": recent.map { v -> [String: Any] in
                [
                    "kind":        v.kind.rawValue,
                    "reason":      v.reason,
                    "cause":       v.cause ?? "",
                    "detected_at": ISO8601DateFormatter().string(from: v.detectedAt),
                ]
            },
        ]
        try writeJSON(payload, to: url)
    }

    /// processing_log 全表 — 无 PII,只有 status / 时戳 / retry。
    private static func writeProcessingLog(to url: URL) throws {
        let store = ProcessingLogStore()
        let rows = store.allRows().map { r -> [String: Any] in
            [
                "date":             r.date,
                "raw":              r.raw.rawValue,
                "event":            r.event.rawValue,
                "impact":           r.impact.rawValue,
                "classify":         r.classify.rawValue,
                "distill":          r.distill.rawValue,
                "personality":      r.personality.rawValue,
                "active_processor": r.activeProcessor ?? "",
                "heartbeat_ms":     r.heartbeatMs ?? 0,
                "retry_count":      r.retryCount,
                "updated_at_ms":    r.updatedAtMs,
            ]
        }
        try writeJSON(["rows": rows], to: url)
    }

    /// db_stats.json — 各表 row count + ~/.portrait 各子目录 du。
    private static func writeDbStats(to url: URL) throws {
        var dict: [String: Any] = [:]
        dict["db_path"] = Storage.portraitDBPath
        dict["db_size_bytes"] = fileSize(Storage.portraitDBPath)
        dict["table_row_counts"] = readTableCounts()

        var dirs: [String: Int64] = [:]
        for (name, url) in [
            ("portrait",        Storage.portraitDir),
            ("events",          Storage.eventsDir),
            ("audio_queue",     Storage.audioQueueDir),
            ("raw_data",        Storage.rawDataDir),
            ("frames",          Storage.framesDir),
            ("video",           Storage.videoDir),
            ("logs",            Storage.dailyLogsDir),
            ("journal",         Storage.journalDir),
        ] {
            dirs[name] = directorySize(url)
        }
        dict["dir_sizes_bytes"] = dirs

        try writeJSON(dict, to: url)
    }

    private static func readTableCounts() -> [String: Int] {
        // 直接用 sqlite3 命令行(避免引 GRDB)。
        let tables = [
            "frames", "video_chunks",
            "audio_chunks", "audio_transcriptions",
            "typing_events", "keystroke_log", "writing_records",
            "processing_log", "speakers", "speaker_samples",
        ]
        var out: [String: Int] = [:]
        for t in tables {
            if let n = sqliteScalarInt("SELECT COUNT(*) FROM \(t)") {
                out[t] = n
            }
        }
        return out
    }

    private static func sqliteScalarInt(_ sql: String) -> Int? {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/sqlite3")
        p.arguments = [Storage.portraitDBPath, sql]
        let out = Pipe()
        p.standardOutput = out
        p.standardError = Pipe()
        do { try p.run(); p.waitUntilExit() } catch { return nil }
        let data = try? out.fileHandleForReading.readToEnd()
        guard let s = data.flatMap({ String(data: $0, encoding: .utf8) })?
            .trimmingCharacters(in: .whitespacesAndNewlines),
              let n = Int(s) else { return nil }
        return n
    }

    /// 过去 24h 所有 com.myportrait.* unified-log 条目,一行一个 JSON。
    /// **本进程作用域** —— OSLogStore(.currentProcessIdentifier) 不需要特殊权限。
    private static func writeOSLog24h(to url: URL) throws {
        let store = try OSLogStore(scope: .currentProcessIdentifier)
        let cutoff = Date().addingTimeInterval(-24 * 3600)
        let position = store.position(date: cutoff)
        let predicate = NSPredicate(format: "subsystem BEGINSWITH 'com.myportrait'")
        let entries = try store.getEntries(at: position, matching: predicate)

        FileManager.default.createFile(atPath: url.path, contents: nil)
        guard let h = try? FileHandle(forWritingTo: url) else { return }
        defer { try? h.close() }

        let isoFmt = ISO8601DateFormatter()
        isoFmt.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        for e in entries {
            guard let log = e as? OSLogEntryLog else { continue }
            let line: [String: Any] = [
                "ts":        isoFmt.string(from: log.date),
                "level":     osLogLevelName(log.level),
                "subsystem": log.subsystem,
                "category":  log.category,
                "msg":       log.composedMessage,
            ]
            guard let data = try? JSONSerialization.data(withJSONObject: line, options: []),
                  let s = String(data: data, encoding: .utf8) else { continue }
            try? h.write(contentsOf: Data((s + "\n").utf8))
        }
    }

    private static func osLogLevelName(_ level: OSLogEntryLog.Level) -> String {
        switch level {
        case .debug:    return "debug"
        case .info:     return "info"
        case .notice:   return "notice"
        case .error:    return "error"
        case .fault:    return "fault"
        case .undefined: return "undefined"
        @unknown default: return "unknown"
        }
    }

    // MARK: - zip + 路径工具

    /// 用系统 `/usr/bin/zip -r` 打包,避免引第三方 ZipFoundation。
    private static func runZip(srcDir: URL, dstZip: URL) throws {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        // -r 递归,-q 静默,cd 到 src 父目录这样压进 zip 的路径相对干净。
        p.arguments = ["-r", "-q", dstZip.path, srcDir.lastPathComponent]
        p.currentDirectoryURL = srcDir.deletingLastPathComponent()
        try p.run()
        p.waitUntilExit()
        guard p.terminationStatus == 0 else {
            throw NSError(domain: "DiagnosticBundle", code: Int(p.terminationStatus),
                          userInfo: [NSLocalizedDescriptionKey: "zip exited with \(p.terminationStatus)"])
        }
    }

    private static func downloadsURL() throws -> URL {
        let urls = FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask)
        guard let url = urls.first else {
            throw NSError(domain: "DiagnosticBundle", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "Couldn't locate Downloads directory"])
        }
        return url
    }

    private static func writeJSON(_ obj: Any, to url: URL) throws {
        let data = try JSONSerialization.data(
            withJSONObject: obj,
            options: [.prettyPrinted, .sortedKeys])
        try data.write(to: url, options: .atomic)
    }

    private static func fileSize(_ path: String) -> Int64 {
        let attrs = try? FileManager.default.attributesOfItem(atPath: path)
        return (attrs?[.size] as? Int64) ?? 0
    }

    /// 递归算目录总大小(allocated size,跟 Finder 显示对齐)。
    /// 失败 / 不存在返回 0。
    private static func directorySize(_ url: URL) -> Int64 {
        let fm = FileManager.default
        guard fm.fileExists(atPath: url.path) else { return 0 }
        var total: Int64 = 0
        guard let en = fm.enumerator(at: url,
                                     includingPropertiesForKeys: [.totalFileAllocatedSizeKey],
                                     options: [.skipsHiddenFiles],
                                     errorHandler: nil) else { return 0 }
        for case let u as URL in en {
            let v = try? u.resourceValues(forKeys: [.totalFileAllocatedSizeKey])
            total += Int64(v?.totalFileAllocatedSize ?? 0)
        }
        return total
    }

    private static func hostArch() throws -> String {
        var size: size_t = 0
        sysctlbyname("hw.machine", nil, &size, nil, 0)
        var buf = [CChar](repeating: 0, count: size)
        sysctlbyname("hw.machine", &buf, &size, nil, 0)
        return String(cString: buf)
    }
}
